AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'
  
  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

Resources:

  # Log group
  PnRaddBffLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-radd-bff"
        LogGroupPrefix: '/aws/ecs'

  PnDocumentReadyTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub '${ProjectName}-document-ready'
      AttributeDefinitions:
        - AttributeName: "fileKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "fileKey"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TimeToLiveSpecification:
        AttributeName: expiringAt
        Enabled: true

Outputs:
  PnDocumentReadyTableArn:
    Description: ARN Dynamo Name used by application to access the key-value store of PnDocumentReadyTable
    Value: !Sub '${PnDocumentReadyTable.Arn}'
  PnDocumentReadyTableName:
    Description: Name of dynamodb table containing notifications
    Value: !Ref PnDocumentReadyTable
  EcsLogGroup:
    Value: !GetAtt PnRaddBffLogGroup.Outputs.LogGroupName
