version: "3.9"
services:
  mockserver:
    image: mockserver/mockserver
    ports:
      - '1080:1080'
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/*.json
      - MOCKSERVER_ENABLE_CORS_FOR_API="true"
      - MOCKSERVER_ENABLE_CORS_FOR_ALL_RESPONSES="true"
    volumes:
      - ./mock_rest_configs:/config
    networks:
      - develop-network

networks:
  develop-network:
    driver: bridge
